# Generated by Django 3.1.1 on 2020-10-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_applyjob_applying_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='applying_for',
            new_name='applied_for',
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='file',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
